---
title: "p8105_hw5_hz3023"
author: "Huiyi Zhu"
date: "2025-11-14"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prepare
```{r}
library(tidyverse)
```

## Problem 1
```{r}
birthday = function(n) {
    days = sample(1:365, size = n, replace = TRUE)
    length(unique(days))<n
}
set.seed(123)

set.seed(20)
result =
  expand_grid(
    group_size = 2:50,
    iter = 1:10000)|>
  mutate(share_bday = map_lgl(group_size, birthday))|>
  group_by(group_size) |>
  summarize(prob_sharebday = mean(share_bday))

result |>
  ggplot(
    aes(x = group_size, 
        y = prob_sharebday)) +
  geom_line() +
  geom_point() +
  labs(
    x = "Group size",
    y = "Probability of shared birthday",
    title = "Group size and Probability of shared birthday"
  )
```

In this plot we can see that the probability of at least two people sharing a birthday increase when group size grows. When the group size reaches near 25, the probability exceeds 50%. After about  50 people, the probability is very close to 1, which indicates that two people shared a birthday are almost guaranteed.
